java -cp .\target\org.reldb.relang.relang-0.0.1-SNAPSHOT.jar;"target\lib\*" Relang < test01.sil
java -cp .\target\org.reldb.relang.relang-0.0.1-SNAPSHOT.jar;"target\lib\*" Relang < test02.sil
java -cp .\target\org.reldb.relang.relang-0.0.1-SNAPSHOT.jar;"target\lib\*" Relang < test03.sil
java -cp .\target\org.reldb.relang.relang-0.0.1-SNAPSHOT.jar;"target\lib\*" Relang < test04.sil
java -cp .\target\org.reldb.relang.relang-0.0.1-SNAPSHOT.jar;"target\lib\*" Relang < test05.sil
java -cp .\target\org.reldb.relang.relang-0.0.1-SNAPSHOT.jar;"target\lib\*" Relang < test06.sil
java -cp .\target\org.reldb.relang.relang-0.0.1-SNAPSHOT.jar;"target\lib\*" Relang < test07.sil
java -cp .\target\org.reldb.relang.relang-0.0.1-SNAPSHOT.jar;"target\lib\*" Relang < test08.sil
java -cp .\target\org.reldb.relang.relang-0.0.1-SNAPSHOT.jar;"target\lib\*" Relang < test09.sil
java -cp .\target\org.reldb.relang.relang-0.0.1-SNAPSHOT.jar;"target\lib\*" Relang < test10.sil
java -cp .\target\org.reldb.relang.relang-0.0.1-SNAPSHOT.jar;"target\lib\*" Relang < test11.sil
java -cp .\target\org.reldb.relang.relang-0.0.1-SNAPSHOT.jar;"target\lib\*" Relang < test12.sil
java -cp .\target\org.reldb.relang.relang-0.0.1-SNAPSHOT.jar;"target\lib\*" Relang < test13.sil
java -cp .\target\org.reldb.relang.relang-0.0.1-SNAPSHOT.jar;"target\lib\*" Relang < test14.sil